/* Generated By:JavaCC: Do not edit this line. gramaticaConstants.java */
package listanumerosascendentes;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface gramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int numero = 5;
  /** RegularExpression Id. */
  int coma = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<numero>",
    "\",\"",
  };

}
